#!/usr/bin/env bash
# Function to perform DNS lookup and use awk for formatting
perform_dns_lookup() {
    local sub_domain="$1"
    local domain="$2"

    # Use dig to perform DNS lookup and format the output using awk
    dig_output=$(dig +short "${sub_domain}.${domain}")

    if [ -z "$dig_output" ]; then
        echo "No record found for ${sub_domain}.${domain}"
    else
        echo "The subdomain ${sub_domain} is a A record and points to ${dig_output}"
    fi
}

# Function to perform DNS query and extract information
query_dns() {
    local sub_domain="$1"
    local domain="$2"

    # Perform DNS lookup using the perform_dns_lookup function
    perform_dns_lookup "${sub_domain}" "${domain}"
}

# Main script
if [ "$#" -eq 1 ]; then
    # When only the domain parameter is provided
    subdomains=("www" "lb-01" "web-01" "web-02")

    for sub_domain in "${subdomains[@]}"; do
        query_dns "${sub_domain}" "$1"
    done
elif [ "$#" -eq 2 ]; then
    # When both domain and subdomain parameters are provided
    query_dns "$2" "$1"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi
